language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
services:
  - redis-server
  - memcached
script:
  - cargo build --verbose --all-features
  - cargo test --verbose --all-features
